# Generated by Django 5.2.4 on 2025-08-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_message_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receipt",
            new_name="receipient",
        ),
    ]
