# Generated by Django 5.2.4 on 2025-08-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_receipient_message_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="recipient",
            new_name="receipient",
        ),
    ]
