# Generated by Django 5.2.4 on 2025-08-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_recipient_message_receipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receipient",
            new_name="recipient",
        ),
    ]
