# Generated by Django 5.2.4 on 2025-08-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_receipient_message_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
