# Generated by Django 5.2.4 on 2025-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
